[project]
name = ""
version = ""
description = ""
authors = [
    {name = "paralevi",email = "paralevi@live.com"},
]
dependencies = [
    "loguru>=0.7.2",
    "dynaconf>=3.2.4",
]
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}

